version: "3.1"
services:
  postgresql:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass # if you login with root, username is 'root'
    ports:
      - 3306:3306 # make sure you don't have another container running on 3306
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017 # make sure we don't have another mongo container running on same port
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data/mongo
        target: /data/mongo/db

networks:
  docker-db:
