services:
  # Postgres Sql database
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # make sure you don't have another container running on 5432

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=q8X7JiGEakDfYScg
  # Mysql database
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      # - MYSQL_DATABASE=example_db
      # - MYSQL_USER=test
      # - MYSQL_PASSWORD=test@123
      - MYSQL_ROOT_PASSWORD=q8X7JiGEakDfYScg
    ports:
      - 3306:3306 # make sure you don't have another container running on 3306
    volumes:
      - ./data/mysql_data:/var/lib/mysql
  # Redis database
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis-data:/data
  # Mongodb database
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017 # make sure we don't have another mongo container running on same port
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=q8X7JiGEakDfYScg
    volumes:
      - ./data/mongo_data/:/data/db/
