version: "3.1"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017 # make sure we don't have another mongo container running on same port
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./db_data:/data/db
    networks:
      - mongo-db

networks:
  mongo-db:
    driver: bridge
