version: "3.1"
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./db_data:/data
    networks:
      - redis-db

networks:
  redis-db:
    driver: bridge
